# Generated by Django 4.2 on 2023-04-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='createData',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='finishedData',
            field=models.DateField(blank=True, null=True),
        ),
    ]
