# Generated by Django 4.2 on 2023-05-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_note_createdata_alter_note_finisheddata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='createData',
        ),
        migrations.RemoveField(
            model_name='note',
            name='finishedData',
        ),
        migrations.AddField(
            model_name='note',
            name='cData',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='fData',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
